### ISSUE TITLE
Testing PA1010D with python : No module named pa1010d

### ISSUE THREAD

**Issue by romane-echino** [pimoroni/pa1010d-python#5]
Hi! 

I just recieved a PA1010d GPS and wanted to test it. I'm not much of a python programmer but after many tries I made it work with NodeJS on I2C. But I don't recieve any data everything's seems to be blank.

I saw a video of someone using the same chip but for an arduino. So I asked myself is the problem wasn't Node after all so I downloaded (with git) and installed (via install.sh) your python module as described in your MD and after a reboot tried to run the sample you provided and here's the output :

```bash
pi@examples$ python latlon.py 
Traceback (most recent call last):
  File "latlon.py", line 4, in <module>
    from pa1010d import PA1010D
ImportError: No module named pa1010d
```

Can you help me with that?

I'm running Raspberry OS 5.10 with Python 2.7.16 on a Compute Module 4 (4GB RAM 8GB eMMC) plugged on a Compute IO Board. And since in NodeJS I'm seeing some data it seems that the pi is correctly configured and plugged to the PA1010D:

NodeJS software data sample :
```bash
Command::GGA::Time/Position
time : 23:30:33
position : lat  - long  q 0
```

**Comment by Gadgetoid** [comment]
I'm a day late and a dollar short here - sorry - but PA1010D is only compatible with Python 3, whereas "python" probably runs ~2.7-

Run with:

```
python3 latlon.py
```
