### ISSUE TITLE
Adding Access to Geoidal Separation Value

### ISSUE THREAD

**Issue by AlexLandherr** [pimoroni/pa1010d-python#6]
I have recently purchased a PA1010D GNSS breakout for my Pi Zero W project. To my slight surprise the otherwise excellent library doesn't have an easy way of calculating the HAE (height above ellipsoid, in the GPS case the WGS84 ellipsoid).

This is done by adding the orthometric height (aka MSL or mean sea level) to the geoidal separation (aka geoid height). I tried cloning the repo and then modifying this file: pa1010d-python/library/pa1010d/__init__.py.

This did not work and I am now asking the developers to make the "geo_sep" value accessible like it is in the pynmea2 library.

Terminology reference:
https://eos-gnss.com/elevation-for-beginners

This would be a nice quality of life change for some people like me that use this breakout and want a little more access without messing with the library code.

The addition of this change would be highly appreciated by me.

**Comment by Gadgetoid** [comment]
> Terminology reference:
> https://eos-gnss.com/elevation-for-beginners

Thank you. I understood basically none of your request so I may need to brush up on this.

The pynmea2 library underpins this library, so it may just be a case of bolting in the right part of it. Do you have any reference to or example usage of this in pynmea2?

**Comment by Gadgetoid** [comment]
Looks like the changes discussed on the Pi forums- with a complete example toward the end- might be worth integrating here? - https://forums.raspberrypi.com/viewtopic.php?t=314666

I'll have a go at integrating those changes in a branch for you to try.

**Comment by AlexLandherr** [comment]
Thanks for the effort! I’ll try them out once I get access to the Pi Zero WH I’m running it from.

Skickat från min iPad

**Comment by Gadgetoid** [comment]
PR raised: https://github.com/pimoroni/pa1010d-python

Assuming I haven't mucked anything up, and you find the time - you should be able to test by cloning & installing this version from source:

```
git clone https://github.com/pimoroni/pa1010d-python -b patch-geo-sep
cd pa1010d-python/library
python3 setup.py install --user
```

**Comment by AlexLandherr** [comment]
Thanks! I'll try it this weekend.

**Comment by AlexLandherr** [comment]
I've now tried it and the preliminary results are good.

**Comment by Gadgetoid** [comment]
Thank you for taking the time to give it a go! I'll merge and release as soon as I can.

**Comment by AlexLandherr** [comment]
Though I'm planning on running it from a Pi Zero 2 W once I get the ones
I've ordered.

Den mån 8 nov. 2021 kl 12:12 skrev Philip Howard ***@***.***>:

**Comment by AlexLandherr** [comment]
Is it possible to have the geo_sep value be of the type "float" instead of "str"? I noticed that when testing the branch the last weekend.

Also I'll now need to reinstall the library after your merge if I'm not mistaken?

**Comment by Gadgetoid** [comment]
I have, in fact, just released it. I'll have to patch float->str in the next release.

You should be able to upgrade from pypi now.

**Comment by AlexLandherr** [comment]
Now when I run it the first data point that comes out is of:
`
<class 'NoneType'>
`

Why is that?

**Comment by Gadgetoid** [comment]
That's a long and busy line of code you've got there, if you use the pattern from the example:

https://github.com/pimoroni/pa1010d-python/blob/5525c58906b75392462467b54dd9e039dcbc08d3/examples/latlon.py#L9-L25

Then you don't need to do any conversion or rounding to the variables, you can do these in the format string, eg:

```python
while True:
    result = gps.update()
    if result:
        print("""
T: {timestamp}
N: {latitude:0.5f}
E: {longitude:0.5f}
""".format(**gps.data))
    time.sleep(1.0)
```


Though the docs on string formatting are... quite intimidating - https://docs.python.org/3/library/string.html#formatstrings

The token `{latitude:0.5f}` will round to 5 decimal places for you.

The weird `**gps.data` bit is the spread operator on `gps.data`, it just unpacks the keys/values into arguments for `format()`.

**Comment by AlexLandherr** [comment]
Thanks for the help, I'm going to use your library in combination with a SparkFun 20x4 Character LCD to make a little GPS navigator. All on a Pi Zero 2 W.

**Comment by AlexLandherr** [comment]
> That's a long and busy line of code you've got there, if you use the pattern from the example:
> 
> 
> 
> https://github.com/pimoroni/pa1010d-python/blob/5525c58906b75392462467b54dd9e039dcbc08d3/examples/latlon.py#L9-L25
> 
> 
> 
> Then you don't need to do any conversion or rounding to the variables, you can do these in the format string, eg:
> 
> 
> 
> ```python
> 
> while True:
> 
>     result = gps.update()
> 
>     if result:
> 
>         print("""
> 
> T: {timestamp}
> 
> N: {latitude:0.5f}
> 
> E: {longitude:0.5f}
> 
> """.format(**gps.data))
> 
>     time.sleep(1.0)
> 
> ```
> 
> 
> 
> 
> 
> Though the docs on string formatting are... quite intimidating - https://docs.python.org/3/library/string.html#formatstrings
> 
> 
> 
> The token `{latitude:0.5f}` will round to 5 decimal places for you.
> 
> 
> 
> The weird `**gps.data` bit is the spread operator on `gps.data`, it just unpacks the keys/values into arguments for `format()`.
> 
> 
> 
> 

Is there a way to truncate the values without rounding?

**Comment by Gadgetoid** [comment]
That's a good question- all floating point formatting rounds because it's a sensible default.

Python seems to have no good way to *truncate* a value, but you can do something like:

```python
value = int(value * 10 ** N) / 10 ** N
```

Where `N` is the number of decimal places.

You can chuck this into a function:

```python
def truncate(value, precision):
    return int(value * 10 ** precision) / 10 ** precision
```

**Comment by AlexLandherr** [comment]
> That's a good question- all floating point formatting rounds because it's a sensible default.
> 
> 
> 
> Python seems to have no good way to *truncate* a value, but you can do something like:
> 
> 
> 
> ```python
> 
> value = int(value * 10 ** N) / 10 ** N
> 
> ```
> 
> 
> 
> Where `N` is the number of decimal places.
> 
> 
> 
> You can chuck this into a function:
> 
> 
> 
> ```python
> 
> def truncate(value, precision):
> 
>     return int(value * 10 ** precision) / 10 ** precision
> 
> ```
> 
> 
> 
> 
> 
> 
> 
> 

Thanks for help again! Is it okay if I keep asking questions in this thread despite the original issues being solved?

**Comment by Gadgetoid** [comment]
> Thanks for help again! Is it okay if I keep asking questions in this thread despite the original issues being solved?

Sure, it's good for this to be somewhere someone might stumble upon it and find the answer they need.

I am at the distinct disadvantage that I don't really *use* the pa1010d to do anything useful, so someone with a good use case and some questions can be helpful and might inform a new example. (we have precious few code examples here)

**Comment by AlexLandherr** [comment]
Thanks! I too think it's good to let others see our problems and their
respective solutions.

Den lör 22 jan. 2022 kl 15:41 skrev Philip Howard ***@***.***
